### ISSUE TITLE
GodotUtilities.SourceGenerators does not exist in Nuget for 4.0.0

### ISSUE THREAD

**Issue by RealityStop** [firebelley/GodotUtilities#6]
Hi Firebelley!  

The new 4.0 version looks great, and I can totally build the source to get it, but nuget doesn't have the source generators package, so it won't install into a project as docs indicate:

https://www.nuget.org/packages/GodotUtilities.SourceGenerators/

**Comment by firebelley** [comment]
Oops, apparently I don't understand the C# ecosystem very well 🙈

Thanks for pointing this out, it should be fixed now!
